### ISSUE TITLE
‘manifest_name’ error

### ISSUE THREAD

**Issue by LiuYunjia** [DCAN-Labs/nda-abcd-s3-downloader#27]
Hello everyone! 
I have some trouble downloading the imaging data from ABCD.
Here is the error: 
----------------------------------------------------------
Reading in S3 links...
Traceback (most recent call last):
  File "/Users/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'manifest_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nda-abcd-s3-downloader-master/download.py", line 386, in <module>
    _cli()
  File "/Users/nda-abcd-s3-downloader-master/download.py", line 125, in _cli
    s3_links_arr = manifest_df[manifest_df['manifest_name'].isin(manifest_names)]['associated_file'].values 
  File "/Users/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'manifest_name'
-----------------------------------------
Is there something wrong with my pandas?

**Comment by arueter1** [comment]
Thanks for your question @LiuYunjia ! We will get back to you with an answer as soon as we are able.

**Comment by perronea** [comment]
@LiuYunjia Looks like it is an issue with your `datastructure_manifest.txt` file. Can you confirm that it contains a column titled "manifest_name"?

**Comment by perronea** [comment]
Closed due to inactivity and inability to reproduce error.
