### ISSUE TITLE
"KeyError: 'manifest_name'"

### ISSUE THREAD

**Issue by kahinimehta** [DCAN-Labs/nda-abcd-s3-downloader#46]
Hi all, I am running into an issue when trying to download data from one subject. After verifying the complete data manifest had been downloaded, I ran the command: 
`python download.py -m /Users/kahinim/Desktop/Package_1210637/datastructure_manifest.txt -s /Users/kahinim/Desktop/subject.txt -o /Users/kahinim/Desktop`

but am getting this error: 
<img width="890" alt="Screen Shot 2023-03-10 at 4 51 24 PM" src="https://user-images.githubusercontent.com/68132139/224435397-b4e55aa3-15fa-4ae4-bad6-980c39b9845e.png">

I was hoping for some guidance on this matter - thank you!

**Comment by perronea** [comment]
@kahinimehta can you email a copy of the datastructure manifest that you are using to perr0372@umn.edu? I know you've had an issue with that file before and re-downloaded it so I'm surprised that you're still having problems with it. That KeyError is coming from a missing header in the manifest so that file you're downloading from the NDA must still not be correct.

**Comment by perronea** [comment]
For some reason the first line of your datastructure_manifest.txt is "Executive" as opposed to the column headers that the code expects. If you're sure you haven't made any edits to that file I would contact the NDA Helpdesk to figure out what's going on. In the meantime if you remove that line you should be good.

**Comment by kahinimehta** [comment]
Thank you - I will contact them and try again after removing that line!

**Comment by kahinimehta** [comment]
Hmm,  I am now getting this traceback: 

```
Traceback (most recent call last):
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/download.py", line 89, in <module>
    main()
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/download.py", line 85, in main
    ABCC_Downloader = Downloader(args)
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/Downloader.py", line 172, in __init__
    self.start()
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/Downloader.py", line 229, in start
    for package_file_list in self.generate_download_file_ids():
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/Downloader.py", line 246, in generate_download_file_ids
    package_files = self.query_package_files_by_s3_url(self.s3_links_arr[batch_start:batch_end])
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/Downloader.py", line 258, in query_package_files_by_s3_url
    response = post_request(url, list(s3_path_list), auth=self.auth, error_handler=HttpErrorHandlingStrategy.reraise_status)
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/utils.py", line 228, in post_request
    error_handler(tmp)
  File "/Users/kahinim/Desktop/Repos/nda-abcd-s3-downloader/src/utils.py", line 82, in reraise_status
    response.raise_for_status()
  File "/Users/kahinim/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://nda.nih.gov/api/package/None/files
```
where `subject.txt` is in the format: `sub-XXXX`
@perronea

**Comment by perronea** [comment]
@kahinimehta You must provide the package id of the data package that you created on the NDA website. That is a required argument and it should've returned an error before getting to this point. I will add this to a list of priority feature requests.

Thank you for testing this code! This is helpful feedback :)

Side note, please open new issues as they arise so that we can more easily keep track of them and make sure that they get addressed properly.

**Comment by kahinimehta** [comment]
@perronea thank you so much again! I will keep this in mind if anything else comes up.
