### ISSUE TITLE
Error tokenizing data

### ISSUE THREAD

**Issue by YaoMeng94** [DCAN-Labs/nda-abcd-s3-downloader#55]
Hi, 
    I have follow the guidance of this repoistry including create the 2 data packages, and creating the kering, when I downloading the packages, it keeps pop out this error message after input NDA account name. Does anyone know this problem?
thanks
**The cmd I run is:** 
python download.py -m ~/Dataset/ABCC/List/ABCC04292023Doc/datastructure_manifest.txt -o ~/Dataset/ABCC/Data -d ~/Dataset/ABCC/List/data_subsets_ABCC-anatomical.txt -wt 10 -l ~/Dataset/ABCC/List/Logs -dp xxxxxxx
**Error Message from the terminal:**
/share/home/yaomeng/Dataset/ABCC/Script/nda-abcd-s3-downloader-master/src/Downloader.py:146: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  self.manifest = pd.read_csv(args.manifest_file,'\t')
Traceback (most recent call last):
  File "download.py", line 89, in <module>
    main()
  File "download.py", line 85, in main
    ABCC_Downloader = Downloader(args)
  File "/share/home/yaomeng/Dataset/ABCC/Script/nda-abcd-s3-downloader-master/src/Downloader.py", line 146, in __init__
    self.manifest = pd.read_csv(args.manifest_file,'\t')
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/share/home/yaomeng/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 1304020

**Comment by YaoMeng94** [comment]
I have checked the datastructure_manifest.txt file, row 1304020 is broken, after I delete this row it's been OK.
